### ISSUE TITLE
QA Report failing to process URLs.

### ISSUE THREAD

**Issue by anjackson** [ukwa/python-w3act#21]
Some weird behaviour today. The QA Reports started failing, as run by these two configurations:

https://github.com/ukwa/ukwa-services/blob/0eaa5b0ce17c0f698b7aac2c1e2808f9447a60de/manage/airflow/dags/w3act_data.py#L428-L438

These are running as a tagged container, `ukwa/python-w3act:2.2.0`, and so the code should be be able to change.

The initial errors were about failing to download a list of TLD/public suffixes. @anjackson assumed this was cached in the `tldextract` package but is now sufficiently old that the library is attempting to download a fresh version. This needed the Airflow DAG configuration to be changed to set `HTTPS_PROXY` so that the download could work.

However, there was another error present, and fixing the download did not fix this:

```
Traceback (most recent call last):
File "/usr/local/bin/w3act-qa-check", line 33, in 
sys.exit(load_entry_point('python-w3act===-.-.-', 'console_scripts', 'w3act-qa-check')())
File "/usr/local/lib/python3.7/site-packages/python_w3act-_._._-py3.7.egg/w3act/dbc/identify_target_qa_issues.py", line 276, in main
File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 4138, in apply
mapped = lib.map_infer(values, f, convert=convert_dtype)
File "pandas/_libs/lib.pyx", line 2467, in pandas._libs.lib.map_infer
File "/usr/local/lib/python3.7/site-packages/python_w3act-_._._-py3.7.egg/w3act/dbc/identify_target_qa_issues.py", line 126, in multiple_domains
TypeError: object of type 'float' has no len()
```

This is quite odd, and appears to imply that the `urls` field of the target data has starting being interpreted as a `float`.

@ldbiz can you see if you can reproduce this error, running the tools locally?

**Comment by ldbiz** [comment]
Looking at the code, it is likely that pandas is encountering a null (which it treats as a float). It could mean dodgy data but it is odd that it has not been encountered before. If it is a straight data issue (as opposed to an environment/config/transfer corruption thing), it should be reproducible as suggested.

**Comment by anjackson** [comment]
Well, re-running the same job later and it went away. I want to look at changing this process anyway, so i don't think there's any point debugging this as it is now.
