### ISSUE TITLE
Export collections hierarchies as JSON files

### ISSUE THREAD

**Issue by anjackson** [ukwa/python-w3act#22]
Currently, this tool can take the database CSV and generate a bit chunk of JSON that contains the different types of data from W3ACT.  This task involves building on that functionality in order to export each W3ACT Collection as a separate JSON file, so that this data can be made available as an API.  As an example, taking the current system, it's possible to manually extract a collection (collection `4028`) and 'pretty-print' the whole tree:

https://gist.github.com/anjackson/19b3039769918fbd73c09bdaffd6ed98#file-aot-collection-example-json

This task would be to automate that process. Given a subcommand like `csv-to-api-json`, with an output folder as an argument, the tool should:

- Loop through all the top-level collections.
- For each, recursively iterate through the collections and sub-collections. At each level, replace the `target_ids` array with a `target` array that contains the list of targets in that collection.
- Output each top-level collection of a file names `<api-output-folder>/collection/<collection_id>.json`

e.g. the above example would appear in a file like `api/collection/4028.json`

**Comment by anjackson** [comment]
Note: some of the fields, especially in the Targets, are not in use and should be omitted. I've got some experimental code for generating simplified data directly from the W3ACT database, which included:

```
"SELECT target.id, wct_id, title, target.created_at, target.updated_at, license_status, scope, \
originating_organisation, live_site_status, organisation_id, author_id as curator_id, keywords, synonyms, authors, no_ld_criteria_met, \
(professional_judgement OR uk_postal_address OR via_correspondence OR is_top_level_domain OR is_uk_hosting OR is_uk_registration) AS in_scope_npld, \
```

And noted:

```
qaissue_id, special_dispensation, is_in_scope_ip, is_in_scope_ip_without_license, active, summary, date_of_publication NEVER USED!

no_ld_criteria_met can't be trusted!
```

So after the initial generation process is working,  we might want to look at skipping some fields.

**Comment by anjackson** [comment]
I think perhaps we should treat the 'invalid' Targets a bit differently.  Rather than then dropping them, maybe all but the `hidden=true` ones should be included in the output, but have a field added that indicates there is a problem, and what that problem is?  Hmmm...

**Comment by ldbiz** [comment]
That would be fine for this issue I think, but it would mean altering the earlier filter - does including them have consequences elsewhere? If so should it be controlled by a flag? If its not generally a problem beyond reporting it then the field would probably be enough.

**Comment by ldbiz** [comment]
Ah, I think I understand - the invalid targets are already available so no change is needed to the 'bare url' filter, at least for that specifically; I just need to use that table as a secondary lookup in the target population and add the warning. I'm still looking at the "hidden" code to see how that affects things.

**Comment by ldbiz** [comment]
I'm testing a change to include the invalid targets; this utility doesn't use the filter flags (perhaps that can be considered as an enhancement?) and hidden targets can be therefore be filtered by the end user on the flag in the json.
